<?php

/**
 * @file
 * immoklink_markup module.
 * Custom Theming functions for Immoklink Project.
 */

/**
 * Implements hook_theme().
 */
function immoklink_markup_theme() {
  return array(
    'date_format' => array(
      'variables' => array('items' => array(), 'type' => array(), 'attributes' => array()),
    ),
    'immoklink_news' => array(
      'variables' => array(),
    ),
    'books_format' => array(
      'variables' => array(),
    ),
    'gallery_format' => array(
      'variables' => array('items' => array(), 'delta' => array()),
    ),
    'immoklink_gallery' => array(
      'variables' => array(),
    ),
  );
}

/**
 * Theming function for date format.
 */
function theme_date_format(&$variables) {
  $output = '';
  if (!empty($variables['value'])) {
    if (is_numeric($variables['value']) && (int) $variables['value'] == $variables['value']) {
      $timestamp = $variables['value'];
    } else {
      $timestamp = strtotime($variables['value']);
    }

    $date = date('l j F Y', $timestamp);
    $iso_date = format_date($timestamp, 'custom', 'j F Y');
    $output .= '<time datetime="' . $iso_date . '">' . $iso_date . '</time>';
  }

  return $output;
}

/**
 * Theming function for news listings.
 */
function theme_immoklink_news(&$variables) {
  $nodes = $variables['node'];
  $output = '';

  $output .= '<div id="three-columns" class="grid-container" style="display:block;"><ul class="news columns-3">';
  foreach ($nodes as $node) {
    if (isset($node->field_news_image_main[LANGUAGE_NONE])){
      $image_path = $node->field_news_image_main[LANGUAGE_NONE][0]['uri'];
    }
    $image = theme_image_style(array('style_name' => 'listings_image', 'path' => $image_path, 'width' => '', 'height' => '', 'attributes' => array('class' => array('media__image'))));
    $path = '/' . drupal_get_path_alias('node/' . $node->nid);

    $output .= '<li class="media">';
    $output .= '<a class="hoover" href="' . $path .  '">' . $image .
                  '<div class="media__body">
                     <h2>' . $node->title . '</h2>
                     <p>' . $node->field_news_listing_text[LANGUAGE_NONE][0]['value'] . '</p>
                   </div>
                </a>
                </li>';
  }
  $output .= '</ul></div>';

  return $output;
}

/**
 * Theming function for books listings.
 */
function theme_books_format(&$variables) {
  $output = '';
  $paragraph = paragraphs_field_get_entity($variables);
  $images = $paragraph->field_books_bundle_image[LANGUAGE_NONE];
  $icon = '/' . drupal_get_path('theme', 'immoklink_base') . '/images/assets/mag.png';

  $output .= '<h2><p>' . $paragraph->field_books_bundle_title[LANGUAGE_NONE][0]['value'] . '</p></h2>';
  $output .= '<ul class="books columns-3">';
  foreach ($images as $image) {
    $output .= '<li class="media">';

    if(isset($image['uri'])) {
      $image_path = $image['uri'];
      $image = theme_image_style(array('style_name' => 'listings_image', 'path' => $image_path, 'height' => '', 'width' => '', 'attributes' => array('class' => array('media__image'))));
      $full_img = file_create_url($image_path);
    }
    $output .= '<a class="hoover" href="' . $full_img . '">';
    $output .= $image;
    $output .= '<div class="media__body"><div class="inner"><img src="' . $icon . '" /></div></div>';
    $output .= '</a>';
    $output .= '</li>';
  }
  $output .= '</ul><hr />';

  return $output;
}

/**
 * Theming function for gallery.
 */
function theme_gallery_format(&$variables) {
  $output = '';
  $paragraph = paragraphs_field_get_entity($variables[0]);
  $twitter_icon = '/' . drupal_get_path('theme', 'immoklink_base') . '/images/assets/twitter-bird.png';
  $facebook_icon = '/' . drupal_get_path('theme', 'immoklink_base') . '/images/assets/facebook_logo.png';

  global $base_url;
  $path_alias = drupal_lookup_path('alias', current_path());
  $url = $base_url . '/' . $path_alias;

  //gets video link if it exist
  if (isset($paragraph->field_gallery_bundle_video_url[LANGUAGE_NONE])) {
    $video_link = $paragraph->field_gallery_bundle_video_url[LANGUAGE_NONE][0]['value'];
  }

  $image_path = $paragraph->field_gallery_bundle_image[LANGUAGE_NONE][0]['uri'];
  $full_img = file_create_url($image_path);

  $output .= '<li class="slide slide' . $variables[1] . ' init-on-load" data-slide="' . $variables[1] . '">';
  if (isset($paragraph->field_gallery_bundle_video_url[LANGUAGE_NONE])) {
    if (strpos($video_link, 'vimeo')) {
      $video_type = 'vimeo';
    } else if (strpos($video_link, 'youtu')) {
      $video_type = 'youtube';
    }

    $output .= '<a class="btn btn-info venoboxvid" data-gall="gall2" data-type="' . $video_type . '" href="' . $video_link . '?autoplay=1">';
    $output .= '<img class="slide-img" src= "' . $full_img . '">';
    $output .= '</a>';
  } else {
    $output .= '<img class="slide-img" src= "' . $full_img . '">';
  }
  $output .= '<div class="share-overlay"><div class="icon-wrap">';
  $output .= '<a class="no-state" href="https://twitter.com/share?text=Immo+Klink&url=' . $url . '" target="_blank">';
  $output .= '<img src="' . $twitter_icon . '">';
  $output .= '</a>';
  $output .= '<a class="no-state" href="http://www.facebook.com/sharer.php?t=Immo+klink&u=' . $url . '" target="_blank">';
  $output .= '<img src="' . $facebook_icon . '">';
  $output .= '</a>';

  if (isset($paragraph->field_gallery_bundle_overlay_txt[LANGUAGE_NONE])) {
    $output .= '<p class="overlay-text">' . $paragraph->field_gallery_bundle_overlay_txt[LANGUAGE_NONE][0]['value'] . '</p>';
  }

  $output .= '</div></div>';
  if (isset($paragraph->field_gallery_bundle_caption[LANGUAGE_NONE])) {
    $output .= '<div class="caption">' . $paragraph->field_gallery_bundle_caption[LANGUAGE_NONE][0]['value'] . '</div>';
  }
  $output .= '</li>';

  return $output;
}

/**
 * Theming function for gallery listings.
 */
function theme_immoklink_gallery(&$variables) {
  $nodes = $variables['node'];
  $output = '';

  $output .= '<div id="three-columns" class="grid-container" style="display:block;"><ul class="news columns-3">';
  foreach ($nodes as $node) {
    if (isset($node->field_gallery_listing_image[LANGUAGE_NONE])){
      $image_path = $node->field_gallery_listing_image[LANGUAGE_NONE][0]['uri'];
    }


    $image = theme_image_style(array('style_name' => 'listings_image', 'path' => $image_path, 'width' => '', 'height' => '', 'attributes' => array('class' => array('media__image'))));
    $path = '/' . drupal_get_path_alias('node/' . $node->nid);

    $output .= '<li class="media">';
    $output .= '<a class="hoover" href="' . $path .  '">' . $image .
      '<div class="media__body">
                     <h2>' . $node->title . '</h2>';
    if (isset($node->field_gallery_listing_desc[LANGUAGE_NONE])) {
      $output .=  '<p>' . $node->field_gallery_listing_desc[LANGUAGE_NONE][0]['value'] . '</p>';
    }
    $output .= '</div></a></li>';
  }
  $output .= '</ul></div>';

  return $output;
}
