<?php

/**
 * @file
 * immoklink_markup module.
 * Custom Theming functions for Immoklink Project.
 */

/**
 * Implements hook_theme().
 */
function immoklink_markup_theme() {
  return array(
    'date_format' => array(
      'variables' => array('items' => array(), 'type' => array(), 'attributes' => array()),
    ),
    'immoklink_news' => array(
      'variables' => array(),
    ),
  );
}

/**
 * Theming function for date format.
 */
function theme_date_format(&$variables) {
  $output = '';
  if (!empty($variables['value'])) {
    if (is_numeric($variables['value']) && (int) $variables['value'] == $variables['value']) {
      $timestamp = $variables['value'];
    } else {
      $timestamp = strtotime($variables['value']);
    }

    $date = date('l j F Y', $timestamp);
    $iso_date = format_date($timestamp, 'custom', 'j F Y');
    $output .= '<time datetime="' . $iso_date . '">' . $iso_date . '</time>';
  }

  return $output;
}

/**
 * Theming function for news listings.
 */
function theme_immoklink_news(&$variables) {
  $nodes = $variables['node'];
  $output = '';

  $output .= '<div id="three-columns" class="grid-container" style="display:block;"><ul class="news columns-3">';
  foreach ($nodes as $node) {
    $image_path = $node->field_news_image_main[LANGUAGE_NONE][0]['uri'];
    $image = theme_image_style(array('style_name' => 'listings_image', 'path' => $image_path, 'width' => '', 'height' => '', 'attributes' => array('class' => array('media__image'))));
    $path = drupal_get_path_alias('node/' . $node->nid);

    $output .= '<li class="media">';
    $output .= '<a class="hoover" href="' . $path .  '">' . $image .
                  '<div class="media__body">
                     <h2>' . $node->title . '</h2>
                     <p>' . $node->field_news_listing_text[LANGUAGE_NONE][0]['value'] . '</p>
                   </div>
                </a>
                </li>';
  }
  $output .= '</ul></div>';

  return $output;
}
