<?php
/**
 * @file
 * Creates vocabulary and taxonomy terms Working at Wellcome applicable to.
 */

$vocab = array(
  'name' => t('Gallery types'),
  'description' => t('Gallery types'),
  'machine_name' => 'gallery_types',
);
$terms = array(
  'fashion' => array(
    'name' => 'Fashion',
    'description' => '',
  ),
  'reportage' => array(
    'name' => 'Reportage',
    'description' => '',
  ),
  'works' => array(
    'name' => 'Works',
    'description' => '',
  ),
);
