<?php
/**
 * @file
 * Creates vocabulary and taxonomy terms Working at Wellcome applicable to.
 */

$vocab = array(
  'name' => t('Gallery types'),
  'description' => t('Gallery types'),
  'machine_name' => 'gallery_types',
);
$terms = array(
  'everyone' => array(
    'name' => 'Fashion',
    'description' => '',
  ),
  'managers' => array(
    'name' => 'Reportage',
    'description' => '',
  ),
  'tenants' => array(
    'name' => 'Works',
    'description' => '',
  ),
);
