<?php
/**
 * @file
 * fimmoklink_text_formats_and_wysiwyg_profiles.features.filter.inc
 */

/**
 * Implements hook_filter_default_formats().
 */
function fimmoklink_text_formats_and_wysiwyg_profiles_filter_default_formats() {
  $formats = array();

  // Exported format: HTML no media.
  $formats['html_no_media'] = array(
    'format' => 'html_no_media',
    'name' => 'HTML no media',
    'cache' => 1,
    'status' => 1,
    'weight' => 0,
    'filters' => array(
      'filter_autop' => array(
        'weight' => 0,
        'status' => 1,
        'settings' => array(),
      ),
      'media_filter' => array(
        'weight' => 2,
        'status' => 1,
        'settings' => array(),
      ),
    ),
  );

  // Exported format: Plain text.
  $formats['plain_text'] = array(
    'format' => 'plain_text',
    'name' => 'Plain text',
    'cache' => 1,
    'status' => 1,
    'weight' => 10,
    'filters' => array(
      'filter_html_escape' => array(
        'weight' => 0,
        'status' => 1,
        'settings' => array(),
      ),
      'filter_url' => array(
        'weight' => 1,
        'status' => 1,
        'settings' => array(
          'filter_url_length' => 72,
        ),
      ),
      'filter_autop' => array(
        'weight' => 2,
        'status' => 1,
        'settings' => array(),
      ),
    ),
  );

  return $formats;
}
