<?php
/**
 * @file
 * Layout definition for Planer one column in 3 layout.
 */

/**
 * Panel layout definition.
 */
$plugin = array(
  'title'    => t('Planer One Column in 3'),
  'category' => t('Planer'),
  'icon'     => 'planer_one_column_in_3.png',
  'theme'    => 'planer_one_column_in_3',
  'regions'  => array(
    'header'         => t('Header'),
    'content'         => t('Content'),
    'footer'         => t('Footer'),
  ),
);
