<?php
/**
 * @file
 * MWT Sitewide.
 * Exported panels layouts, pages, content-types and mini panels that are used
 * across the whole site.
 */

/**
 * Implements hook_ctools_plugin_api().
 */
function immoklink_sitewide_ctools_plugin_api($module, $api) {
  if ($module == 'panels' && $api == 'styles') {
    return array('version' => 2.0);
  }
  // This module exposes exported panels pages.
  if ($module == 'page_manager' && $api == 'pages_default') {
    return array('version' => 1);
  }
  // This is for mini panels.
  if ($module == "panels_mini" && $api == "panels_default") {
    return array("version" => "1");
  }
  // Now for pm_existing_pages pages.
  if ($module == 'pm_existing_pages' && $api == 'pm_existing_pages') {
    return array('version' => 1);
  }
  if ($module == "ctools_custom_content" && $api == "ctools_content") {
    return array("version" => "1");
  }
}

/**
 * Implements hook_ctools_plugin_directory()
 */
function immoklink_sitewide_ctools_plugin_directory($module, $plugin) {
  if ($module == 'page_manager' || $module == 'panels' || $module == 'ctools') {
    return 'plugins/' . $plugin;
  }
}

/**
 * Implements hook_default_page_manager_pages().
 */
function immoklink_sitewide_default_page_manager_pages() {
  // A page manager page is a custom page, built using panels, which has its
  // own discrete menu path.
  $pages = array();
  $module = 'immoklink_sitewide';
  $path = drupal_get_path('module', $module) . '/plugins/page_manager_pages';
  foreach (glob("{$path}/*.inc") as $file) {
    include($file);
    $pages[$page->name] = $page;
  }
  return $pages;
}

/**
 * Implements hook_default_page_manager_handlers().
 */
function immoklink_sitewide_default_page_manager_handlers() {
  // A page manager handler is an override to an existing page manager task:
  // For example: a custom panel page for the node-view page.
  $handlers = array();
  $module = 'immoklink_sitewide';
  $path = drupal_get_path('module', $module) . '/plugins/page_manager_handlers';
  foreach (glob("{$path}/*.inc") as $file) {
    include($file);
    $handlers[] = $handler;
  }
  return $handlers;
}

/**
 * Implementation of hook_default_panels_mini().
 */
function immoklink_sitewide_default_panels_mini() {
  $minis = array();
  $module = 'immoklink_sitewide';
  $path = drupal_get_path('module', $module) . '/plugins/panels_mini';
  foreach (glob("{$path}/*.inc") as $file) {
    include($file);
    $minis[$mini->name] = $mini;
  }
  return $minis;
}

/**
 * Implementation of hook_default_ctools_custom_content().
 */
function immoklink_sitewide_default_ctools_custom_content() {
  $content_panes = array();
  $module = 'immoklink_sitewide';
  $path = drupal_get_path('module', $module) . '/plugins/content_panes';
  foreach (glob("{$path}/*.inc") as $file) {
    include($file);
    $content_panes[$content->name] = $content;
  }
  return $content_panes;
}

/**
 * Implements hook_ctools_content_subtype_alter().
 */
function immoklink_sitewide_ctools_content_subtype_alter(&$subtype, &$plugin) {
  // Panels UI is bugged. Use a custom icon for Mini panels, so they are easily
  // spotted in the UI.
  if ($plugin['module'] == 'panels_mini') {
    $plugin['icon'] = $subtype['icon'] = drupal_get_path('module', 'immoklink_sitewide') . '/images/mini_panel_icon.png';
  }
}

/**
 * Implements hook_views_api().
 */
function immoklink_sitewide_views_api() {
  return array(
    'api' => '3.0',
  );
}

/**
 * Implements hook_views_default_views().
 */
function immoklink_sitewide_views_default_views() {
  $files = file_scan_directory(drupal_get_path('module', 'immoklink_sitewide') . '/plugins/views', '/inc$/', array('key' => 'filename', 'recurse' => FALSE));
  $views = array();
  if (!empty($files)) {
    foreach ($files as $file) {
      @include ($file->uri);
      $views[$view->name] = $view;
    }
  }
  return $views;
}

/**
 * Implements hook_menu().
 */
function immoklink_sitewide_menu() {
  $items = array();
  $items['gallery-thumbnail/%node'] = array(
    'title' => 'Gallery thumbnail listings',
    'description' => 'Thumbnail listings of gallery image.',
    'page callback' => 'gallery_thumbnail_listings_page',
    'page arguments' => array(1),
    'type' => MENU_CALLBACK,
    'access arguments' => array('access content'),
  );
  $items['news'] = array(
    'title' => 'News listings page',
    'description' => 'News listings page',
    'page callback' => 'news_listings_page',
    'type' => MENU_CALLBACK,
    'access arguments' => array('access content'),
  );
  $items['news/%'] = array(
    'title' => 'News listings',
    'description' => 'News listings page by tags',
    'page callback' => 'news_listings_page_by_tag',
    'page arguments' => array(1),
    'type' => MENU_CALLBACK,
    'access arguments' => array('access content'),
  );
  $items['news-tag-listings'] = array(
    'title' => 'Tags listings',
    'description' => 'List of all the tags',
    'page callback' => 'tags_listings_page',
    'type' => MENU_CALLBACK,
    'access arguments' => array('access content'),
  );

  return $items;
}



///**
// * Callback function.
// */
//function gallery_thumbnail_listings_page($node) {
//  $output = '';
//
//  $output .= '<div class="page"><article><h1>Projects</h1></article>';
//  $images = $node->field_gallery_images[LANGUAGE_NONE];
//
//  $output .= '<div class="content grid"><div class="wrap">';
//  foreach ($images as $image) {
//    $image = paragraphs_field_get_entity($image);
//
//    $image_path = $image->field_gallery_bundle_image[LANGUAGE_NONE][0]['uri'];
//    $image = theme_image_style(array('style_name' => 'gallery_thumbnail', 'path' => $image_path, 'height' => '', 'width' => '', 'attributes' => array('class' => array('fade-me-in'))));
//    $path = '/' . drupal_get_path_alias('node/' . $node->nid);
//    $output .= '<a href="' . $path . '" class="grid-item">';
//    $output .= $image;
//    $output .= '<div class="overlay"></div></a>';
//  }
//  $output .= '</div></div></div>';
//
//  return $output;
//}


///**
// * Gallery thumbnail listing page callback.
// */
//function gallery_thumbnail_listings_page($node) {
//  $output = '';
//  global $base_url;
//
//  $json = $base_url . '/thumbnail-gallery/json/' .  $node->nid;
//
//  $output .= '<h1>' . $node->title . '</h1>';
//  $output .= '<section id="gallery" class="page-gallery clearfix">
//				<div class="grid-sizer"></div>
//			  </section></article><div class="clear-fix"></div></div>';
//  $output .= '<script id="page-index-tpl" type="text/x-jsrender">
//		        <div class="page-index image-{{:orientation}}" id="index-{{:count}}" data-id="{{:id}}" data-href="{{:url}}">
//			        <div class="page-index-slideshow" data-cycle-delay={{:delay}} data-cycle-timeout="{{:timeout}}" data-cycle-auto-height="4:3">
//			        {{for images}}
//			            <img src="{{>#data}}" alt="{{:title}}" title="{{:title}}" data-index-id="{{>#index}}"/>
//			        {{/for}}
//			        </div>
//			    <div class="page-index-overlay" style="display: none;"></div>
//			    </div>
//	        </script>';
//  $output .= '<script type="text/javascript" src="/sites/all/themes/immoklink_base/js/jquery-1.8.3.min.js"></script>
//  <script type="text/javascript" src="/sites/all/themes/immoklink_base/js/masonry.min.js"></script>
//  <script type="text/javascript" src="/sites/all/themes/immoklink_base/js/jsrender.min.js"></script>
//  <script type="text/javascript" src="/sites/all/themes/immoklink_base/js/jquery.cycle2.min.js"></script>';
//
//  $output .= '<script type="text/javascript">
//                var GalleryIndex = function () {};
//
//		GalleryIndex.prototype.endpoint = "' . $json . '";
//
//		GalleryIndex.prototype.pageIndexElement = "gallery";
//
//		GalleryIndex.prototype.pageIndexClass = ".page-gallery";
//
//		GalleryIndex.prototype.pageIndexItemClass = ".page-index";
//
//		GalleryIndex.prototype.pageIndexOverlayClass = ".page-index-overlay";
//
//		GalleryIndex.prototype.pageIndexCaptionClass = ".page-index-caption";
//
//		GalleryIndex.prototype.pageIndexSlideshowClass = ".page-index-slideshow";
//
//		GalleryIndex.prototype.organise = {};
//
//		GalleryIndex.prototype.slideshow = {};
//
//		GalleryIndex.prototype.organiseGrid = function () {};
//
//		GalleryIndex.prototype.overlayCaption = function () {
//          var imageHeight, imageWidth, parent;
//			var self = this;
//
//			$(self.pageIndexItemClass).hover(function (ev) {
//
//              ev.preventDefault();
//
//              imageWidth = $(this).find("img").width();
//              imageHeight = $(this).find("img").height();
//
//              parent = $(this);
//              parent.find(self.pageIndexOverlayClass).width(imageWidth).height(imageHeight).show();
//              parent.find(self.pageIndexCaptionClass).show();
//            }, function (ev) {
//
//              ev.preventDefault();
//
//              parent = $(this);
//              parent.find(self.pageIndexOverlayClass).hide();
//              parent.find(self.pageIndexCaptionClass).hide();
//            });
//
//			$(self.pageIndexOverlayClass).click(function (ev) {
//              ev.preventDefault();
//              window.location.href = $(this).parent().data("href");
//            });
//		};
//
//		GalleryIndex.prototype.run = function () {
//          var pageIndexHtml = $.templates("#page-index-tpl");
//
//          var self = this;
//          var count = 0;
//
//          return $.getJSON(this.endpoint, function (results) {
//
//            if (results && results.hasOwnProperty("data") && results.data.length > 0) {
//
//              $.each(results.data, function(k, v) {
//
//                v.delay = Math.floor(Math.random() * 30000 + 1000);
//                v.timeout = Math.floor(Math.random() * 30000 + 10000);
//                v.count = ++count;
//                $("#" + self.pageIndexElement).append(pageIndexHtml.render(v));
//
//              });
//
//              if ($(self.pageIndexClass).length > 0) {
//                self.organiseGrid();
//
//                self.slideshow = $(self.pageIndexSlideshowClass).cycle({
//							"random": true
//						});
//
//						self.overlayCaption();
//
//					}
//            }
//          });
//        }
//
//		$(function () {
//          var g = new GalleryIndex();
//
//          g.run();
//
//
//        });
//	</script>';
//
//  return $output;
//}

/**
 * Gallery thumbnail listing page callback.
 */
function gallery_thumbnail_listings_page($node) {
  $output = '';
  $output .= '<div class="page">';
  if ($node->title != 'People') {
    $output .= '<h1>' . $node->title . '</h1>';
  }

  $output .= '<div id="bigimages">';
  $images = $node->field_gallery_images[LANGUAGE_NONE];
  $sid = 0;
  foreach ($images as $image) {
    $image = paragraphs_field_get_entity($image);
    $image_path = $image->field_gallery_bundle_image[LANGUAGE_NONE][0]['uri'];
    $image = theme_image_style(array('style_name' => 'gallery_thumbnail', 'path' => $image_path, 'height' => '', 'width' => ''));
    $path = '/' . drupal_get_path_alias('node/' . $node->nid);

    $output .= '<a href="' . $path . '?sid=' . $sid . '">';
    $output .= $image;
    $output .= '</a>';
    $sid++;
  }

  return $output;
}


/**
 * News listings page.
 */
function news_listings_page() {
  $output = '';
  global $base_url;

  $output .= '<div style="display: inline; float: right;"class="all-tags-link"><a href="/news-tag-listings">See all tags</a></div><div class="clear-fix"></div>';
  $output .= '<section id="gallery-highlight" class="page-cover"></section>';
  $form = drupal_get_form('immoklink_sitewide_newsletter_form_single_line');
  $output .= render($form);
  $output .= '<div class="clear-fix"></div>';
  $output .= '<section id="gallery-collection" class="page-grid"></section></article></div>';
  $output .= '<script id="page-cover-tpl" type="text/x-jsrender">
		<div class="page-cover-item clearfix image-{{:~imageOrientation(image)}}" data-id="{{:id}}">
			<div class="page-cover-wrap">
				<span class="page-cover-img">
					<a href="{{:link}}"><img src="{{:image.path}}" alt="{{:title}}" title="{{:title}}"></a>
				</span>
			</div>
			<div class="page-cover-wrap">
				<a href="{{:link}}"><h2>{{:title}}</h2></a>
				<p>{{:description}}</p>
				<em>{{:date}}</em>
				<ul class="page-cover-tags">
					{{for tags}}
					<li>{{:#data}}</a></li>
					{{/for}}
				</ul>

  <div class="icons">
  <a href="http://www.facebook.com/share.php?u={{:link}}&title={{:title}} target="_blank">
  <img class="sm-icon" src="' . $base_url . '/sites/all/themes/immoklink_base/images/assets/facebook_about1.png">
   </a>
  <a class="icon twitter-link" href="https://twitter.com/intent/tweet?original_referer=' . $base_url . '&amp;url={{:link}}&amp;text={{:description}}&amp;via=Immoklink" target="_blank"><img class="sm-icon" src="' . $base_url . '/sites/all/themes/immoklink_base/images/assets/twitter_about1.png"></a>
  </div>

			</div>
		</div>
	</script>';
  $output .= '<script id="page-grid-tpl" type="text/x-jsrender">
		<div class="page-grid-item clearfix image-{{:~imageOrientation(image)}}" data-id="{{:id}}">
			<div class="page-grid-wrap">
				<span class="page-grid-img">
					<a href="{{:link}}"><img src="{{:image.path}}" alt="{{:title}}" title="{{:title}}" ></a>
				</span>
			</div>
			<div class="page-grid-wrap">
				<a href="{{:link}}"><h2>{{:title}}</h2></a>
				<p>{{:description}}</p>
				<em>{{:date}}</em>
				<ul class="page-grid-tags">
					{{for tags}}
					<li>{{:#data}}</li>
					{{/for}}
				</ul>

				 <div class="icons">
  <a href="http://www.facebook.com/share.php?u={{:link}}&title={{:title}} target="_blank">
  <img class="sm-icon" src="' . $base_url . '/sites/all/themes/immoklink_base/images/assets/facebook_about1.png">
   </a>
  <a class="icon twitter-link" href="https://twitter.com/intent/tweet?original_referer=' . $base_url . '&amp;url={{:link}}&amp;text={{:description}}&amp;via=Immoklink" target="_blank"><img class="sm-icon" src="' . $base_url . '/sites/all/themes/immoklink_base/images/assets/twitter_about1.png"></a>
  </div>
			</div>
		</div>
	</script>';

  $output .= '<script type="text/javascript" src="/sites/all/themes/immoklink_base//js/jquery-1.8.3.min.js"></script>
  <script type="text/javascript" src="/sites/all/themes/immoklink_base//js/masonry.min.js"></script>
  <script type="text/javascript" src="/sites/all/themes/immoklink_base//js/jsrender.min.js"></script>';
  $output .= '<script type="text/javascript">

    $.views.helpers({
			imageOrientation: function (val) {
    if (!val || !val.hasOwnProperty("width") || !val.hasOwnProperty("height")) {
      return "unknown";
    }
    return parseInt(val.width) > parseInt(val.height) ? "landscape" : "portrait";
  }
		});


		var Gallery = function () {};

		Gallery.prototype.endpoint = "' . $base_url . '/news/json";

		Gallery.prototype.pageCoverElement = "gallery-highlight";
		Gallery.prototype.pageGridElement= "gallery-collection";

		Gallery.prototype.pageCoverClass = ".page-cover";
		Gallery.prototype.pageGridClass = ".page-grid";

		Gallery.prototype.pageCoverItemClass = ".page-cover-item";
		Gallery.prototype.pageGridItemClass = ".page-grid-item";

    Gallery.prototype.resetGridLayout = function () {
      $(this.pageGridClass).masonry("layout");
    };

		Gallery.prototype.organise = {};

		Gallery.prototype.organiseGrid = function () {
      //if (typeof $.masonry === "function") {
      this.organise = $(this.pageGridClass).masonry({
				  // options
				  itemSelector: this.pageGridItemClass,
				  columnWidth: 290,
				  //percentPosition: true,
				  gutter: 25,
				  initLayout: false,
				  fitWidth: true
				});
			//}
		}

		Gallery.prototype.getImages = function () {
      var pageGridHtml = $.templates("#page-grid-tpl");
      var pageCoverHtml = $.templates("#page-cover-tpl");

      var self = this;

      return $.getJSON(this.endpoint, function (results) {
        if (results && results.hasOwnProperty("data") && results.data.length > 0) {
          $.each(results.data, function(k, v) {
            //populate first three image as cover
            //and rest as grid
            if (v.hasOwnProperty("id") && parseInt(v.id) <= 3) {
              $("#" + self.pageCoverElement).append(pageCoverHtml.render(v));
            } else {
              $("#" + self.pageGridElement).append(pageGridHtml.render(v));
            }
          });

          if ($(self.pageGridClass).length > 0) {
            self.organiseGrid();
            setTimeout(function () {
              self.organise.masonry();
            }, 100);
          }
        }

      });
    }

		var g = new Gallery();

		g.getImages();

    $(window).load(function() {
      g.resetGridLayout();
    });

	</script>';
  return $output;
}

/**
 * Call back for news listings by taxonomy.
 */
function news_listings_page_by_tag($tid) {
  $output = '';

  global $base_url;
  $term = taxonomy_term_load($tid);
  if ($term) {
    if ($term->vocabulary_machine_name == 'news_tags') {
      $output .= '<h1><a href="/news" style="text-decoration: none">News</a> > Tagged with ' . $term->name . '</h1>';
      $output .= '<div class="all-tags-link"><a href="/news-tag-listings">See all tags</a></div><div class="clear-fix"></div>';
      $output .= '<section id="gallery-highlight" class="page-cover"></section>';
      $form = drupal_get_form('immoklink_sitewide_newsletter_form_single_line');
      $output .= render($form);
      $output .= '<div class="clear-fix"></div>';
      $output .= '<section id="gallery-collection" class="page-grid"></section></article></div>';
      $output .= '<script id="page-cover-tpl" type="text/x-jsrender">
		<div class="page-cover-item clearfix image-{{:~imageOrientation(image)}}" data-id="{{:id}}">
			<div class="page-cover-wrap">
				<span class="page-cover-img">
					<a href="{{:link}}"><img src="{{:image.path}}" alt="{{:title}}" title="{{:title}}"></a>
				</span>
			</div>
			<div class="page-cover-wrap">
				<a href="{{:link}}"><h2>{{:title}}</h2></a>
				<p>{{:description}}</p>
				<em>{{:date}}</em>
				<ul class="page-cover-tags">
					{{for tags}}
					<li>{{:#data}}</li>
					{{/for}}
				</ul>
				 <div class="icons">
  <a href="http://www.facebook.com/share.php?u={{:link}}&title={{:title}} target="_blank">
  <img class="sm-icon" src="' . $base_url . '/sites/all/themes/immoklink_base/images/assets/facebook_about1.png">
   </a>
  <a class="icon twitter-link" href="https://twitter.com/intent/tweet?original_referer=' . $base_url . '&amp;url={{:link}}&amp;text={{:description}}&amp;via=Immoklink" target="_blank"><img class="sm-icon" src="' . $base_url . '/sites/all/themes/immoklink_base/images/assets/twitter_about1.png"></a>
  </div>
			</div>
		</div>
	</script>';
      $output .= '<script id="page-grid-tpl" type="text/x-jsrender">
		<div class="page-grid-item clearfix image-{{:~imageOrientation(image)}}" data-id="{{:id}}">
			<div class="page-grid-wrap">
				<span class="page-grid-img">
					<a href="{{:link}}"><img src="{{:image.path}}" alt="{{:title}}" title="{{:title}}" ></a>
				</span>
			</div>
			<div class="page-grid-wrap">
				<a href="{{:link}}"><h2>{{:title}}</h2></a>
				<p>{{:description}}</p>
				<em>{{:date}}</em>
				<ul class="page-grid-tags">
					{{for tags}}
					<li>{{:#data}}</li>
					{{/for}}
				</ul>
				 <div class="icons">
  <a href="http://www.facebook.com/share.php?u={{:link}}&title={{:title}} target="_blank">
  <img class="sm-icon" src="' . $base_url . '/sites/all/themes/immoklink_base/images/assets/facebook_about1.png">
   </a>
  <a class="icon twitter-link" href="https://twitter.com/intent/tweet?original_referer=' . $base_url . '&amp;url={{:link}}&amp;text={{:description}}&amp;via=Immoklink" target="_blank"><img class="sm-icon" src="' . $base_url . '/sites/all/themes/immoklink_base/images/assets/twitter_about1.png"></a>
  </div>
			</div>
		</div>
	</script>';

      $output .= '<script type="text/javascript" src="/sites/all/themes/immoklink_base//js/jquery-1.8.3.min.js"></script>
  <script type="text/javascript" src="/sites/all/themes/immoklink_base//js/masonry.min.js"></script>
  <script type="text/javascript" src="/sites/all/themes/immoklink_base//js/jsrender.min.js"></script>';
      $output .= '<script type="text/javascript">

    $.views.helpers({
			imageOrientation: function (val) {
    if (!val || !val.hasOwnProperty("width") || !val.hasOwnProperty("height")) {
      return "unknown";
    }
    return parseInt(val.width) > parseInt(val.height) ? "landscape" : "portrait";
  }
		});


		var Gallery = function () {};';

      $output .= 'Gallery.prototype.endpoint = "' . $base_url . '/news/json/' . $tid . '";

		Gallery.prototype.pageCoverElement = "gallery-highlight";
		Gallery.prototype.pageGridElement= "gallery-collection";

		Gallery.prototype.pageCoverClass = ".page-cover";
		Gallery.prototype.pageGridClass = ".page-grid";

		Gallery.prototype.pageCoverItemClass = ".page-cover-item";
		Gallery.prototype.pageGridItemClass = ".page-grid-item";

		Gallery.prototype.organise = {};

		Gallery.prototype.organiseGrid = function () {
      //if (typeof $.masonry === "function") {
      this.organise = $(this.pageGridClass).masonry({
				  // options
				  itemSelector: this.pageGridItemClass,
				  columnWidth: 290,
				  //percentPosition: true,
				  gutter: 25,
				  initLayout: false,
				  fitWidth: true
				});
			//}
		}

		Gallery.prototype.getImages = function () {
      var pageGridHtml = $.templates("#page-grid-tpl");
      var pageCoverHtml = $.templates("#page-cover-tpl");

      var self = this;

      return $.getJSON(this.endpoint, function (results) {
        if (results && results.hasOwnProperty("data") && results.data.length > 0) {
          $.each(results.data, function(k, v) {
            //populate first three image as cover
            //and rest as grid
            if (v.hasOwnProperty("id") && parseInt(v.id) <= 3) {
              $("#" + self.pageCoverElement).append(pageCoverHtml.render(v));
            } else {
              $("#" + self.pageGridElement).append(pageGridHtml.render(v));
            }
          });

          if ($(self.pageGridClass).length > 0) {
            self.organiseGrid();
            setTimeout(function () {
              self.organise.masonry();
            }, 100);
          }
        }

      });
    }

		var g = new Gallery();

		g.getImages();

	</script>';
    }
    return $output;
  }
}

/**
 * Callback function.
 */
function tags_listings_page() {
  $output = '';
  global $base_url;
  $output .= '<h1><a href="/news" style="text-decoration: none">News</a> > All tags</h1>';

  $output .= '<div class="clear-left"></div>';

  $vocab = taxonomy_vocabulary_machine_name_load('news_tags');
  $tree = taxonomy_get_tree($vocab->vid);
  $output .= '<ul class="list-unstyled list-lined">';
  foreach ($tree as $term) {
    $countnode = db_query("SELECT COUNT(field_news_tags_tid) AS count FROM {field_data_field_news_tags} WHERE field_news_tags_tid = :field_news_tags_tid", array(':field_news_tags_tid' => $term->tid))->fetchField();

    $output .= '<li class="br-keyline cf">';
    $output .= '<a class="istats--tracker" href="' . $base_url . '/news/' . $term->tid . '">';
    $output .= '<h2 class="delta pull--left no-margin">' . $term->name . '</h2>';
    $output .= '<p class="pull--right no-margin text--shout deemphasize br-page-text-ontext"> ' . $countnode . ' posts </p>';
    $output .= '</a>';
    $output .= '</li>';
  }
  $output .= '</ul>';
  return $output;
}

/**
 * Newsletter signup form.
 */
function immoklink_sitewide_newsletter_form() {
  global $base_url;

  $form['#prefix'] = '<div id="webform-ajax-wrapper-3">
                    <div class="icons">
                    <a href="https://www.facebook.com/immo.klink" class="sm-icon"><img class="sm-icon about-icon" src="' . $base_url . '/sites/all/themes/immoklink_base/images/assets/facebook_about1.png"></a>
                    <a href="https://twitter.com/ImmoKlink" class="sm-icon"><img class="sm-icon about-icon" src="' . $base_url . '/sites/all/themes/immoklink_base/images/assets/twitter_about1.png"></a>
                    <a href="https://www.instagram.com/immoklink/" class="sm-icon"><img class="sm-icon about-icon" src="' . $base_url . '/sites/all/themes/immoklink_base/images/assets/instagram_about1.png"></a>
                    </div>
                    <div class="clear-left"></div>
                    <div class="signup">Sign up for email updates</div>
                     <div class="clear-left"></div>
                    <div id="signup-error"></div>';
  $form['#suffix'] = '</div><div class="clear-left"></div>';
//  $form['my_markup'] = array(
//      '#markup' => '<div class="signup">Sign up for email updates</div>'
//  );
  $form['signup'] = array(
      '#title' => t(" "),
      '#type' => 'textfield',
      '#default_value' => '',
//      '#attributes' => array(
//          'placeholder' => t('email@there.com'),
//      ),
  );
  $form['actions']['submit'] = array(
      '#type' => 'submit',
      '#value' => t('Subscribe'),
  );
  $form['#validate'] = array('immoklink_sitewide_newsletter_form_validate');
  $form['#submit'] = array('immoklink_sitewide_newsletter_form_submit');
  $form['actions']['submit']['#ajax'] = array(
      'callback' => 'immoklink_sitewide_newsletter_form_ajax_callback',
      'event' => 'click',
      'wrapper' => 'newsletter-form',
      'progress' => array(
          'message' => '',
          'type' => 'throbber',
      ),
  );
  return $form;
}

/**
 * Newsletter signup form.
 */
function immoklink_sitewide_newsletter_form_single_line() {
  $form['#prefix'] = '<div class="update-signup" id="update-signup"><div id="signup-error"></div><div id="webform-ajax-wrapper-4">';
  $form['#suffix'] = '</div></div>';
  $form['my_markup'] = array(
      '#markup' => '<div class="signup">Sign up for email updates of our news</div>'
  );
  $form['signup'] = array(
      '#title' => t(" "),
      '#type' => 'textfield',
      '#default_value' => '',
      '#attributes' => array(
          'placeholder' => t('email@there.com'),
      ),
  );
  $form['actions']['submit'] = array(
      '#type' => 'submit',
      '#value' => t('sign up'),
  );
  $form['#validate'] = array('immoklink_sitewide_newsletter_form_validate');
  $form['#submit'] = array('immoklink_sitewide_newsletter_form_submit');
  $form['actions']['submit']['#ajax'] = array(
      'callback' => 'immoklink_sitewide_newsletter_form_ajax_callback',
      'event' => 'click',
      'wrapper' => 'newsletter-form',
      'progress' => array(
          'message' => '',
          'type' => 'throbber',
      ),
  );
  return $form;
}

/**
 * Implements hook_form_alter().
 */
function immoklink_sitewide_form_alter($form, &$form_state, $form_id) {
  if ($form_id == 'gallery_node_form') {
    $form['field_gallery_lading_ordering']['#access'] = FALSE;
  }
}

/*
* Implementation of hook_form_FORM_ID_alter
*
* Hiding taxonomy term description field
*/

function immoklink_sitewide_form_taxonomy_form_term_alter(&$form, &$form_state) {
  $form['description']['#access'] = FALSE;
  $form['relations']['#access'] = FALSE;
}
